var TR = {
  // background
  backgroundTitle: 'Фон',
  backgroundReset: 'Сброс',
  backgroundImport: 'Импорт (jpg, png...)',
  backgroundFill: 'Заполнить',

  // camera
  cameraTitle: 'Камера',
  cameraReset: 'Вид',
  cameraCenter: 'Сброс (bar)',
  cameraFront: 'Спереди (F)',
  cameraLeft: 'Слева (L)',
  cameraTop: 'Сверху (T)',
  cameraMode: 'Режим камеры',
  cameraOrbit: 'Орбита (Вращение)',
  cameraSpherical: 'Сферическая (трекбол)',
  cameraPlane: 'Плоскость (трекбол)',
  cameraProjection: 'Проекция',
  cameraPerspective: 'Перспективная',
  cameraOrthographic: 'Ортогональная',
  cameraFov: 'Фокусное расстояние (мм)',
  cameraPivot: 'Выбор вращения',
  cameraRmbOnly: 'Только ПКМ для камеры',
  cameraSafeMargin: 'Безопасные границы Near/Far',
  cameraSpeedTitle: 'Настройки скорости',
  cameraSpeedTranslate: 'Скорость перемещения',
  cameraSpeedZoom: 'Скорость зума',
  cameraSpeedRotate: 'Скорость вращения',
  cameraSpeedRoll: 'Скорость наклона',

  // reference images
  cameraRefTitle: 'Референсные изображения',
  cameraRef2DMode: 'Режим 2D Панорамирования/Зума',
  cameraRefDrag: 'Интерактивное перемещение',
  cameraRefReset2D: 'Сбросить 2D вид',
  cameraRefAdd: 'Импорт референса',
  cameraRefOpacity: 'Прозрачность',
  cameraRefScale: 'Масштаб',
  cameraRefOffsetX: 'Смещение X',
  cameraRefOffsetY: 'Смещение Y',
  cameraRefRemove: 'Удалить выбранный',
  cameraRefClearAll: 'Очистить все референсы',

  // split viewport
  splitViewportTitle: 'Разделить экран',
  splitViewportOff: 'Выкл',
  splitViewportMirror: 'Зеркало (одна камера)',
  splitViewportIndependent: 'Независимые камеры',
  splitViewportShowInactiveCursor: 'Показывать курсор в неактивном вьюпорте',

  // file
  fileTitle: 'Файл',
  fileImportTitle: 'Импорт',
  fileAdd: 'Добавить(obj,sgl,ply,stl)',
  fileAutoMatrix: 'Масштаб-вид',
  fileVertexSRGB: 'Цвета вершин sRGB',
  fileExportSceneTitle: 'Экспорт сцены',
  fileExportAll: 'Экспорт все',
  fileExportSGL: 'Сохранить .sgl',
  fileExportOBJ: 'Сохранить .obj',
  fileExportPLY: 'Сохранить .ply',
  fileExportSTL: 'Сохранить .stl',

  fileExportTextureTitle: null,
  fileExportTextureSize: null,
  fileExportColor: null,
  fileExportRoughness: null,
  fileExportMetalness: null,

  // scene
  sceneTitle: 'Сцена',
  sceneReset: 'Очистить сцену',
  sceneResetConfirm: 'Подтвердить четкую сцену',
  sceneAddSphere: 'Добавить сферу',
  sceneAddCube: 'Добавить куб',
  sceneAddCylinder: 'Добавить цилиндр',
  sceneAddTorus: 'Добавить тор',
  sceneSelection: 'Выбрать',
  sceneMerge: 'Объединить',
  sceneDuplicate: null,
  sceneDelete: 'Удалить выделение',

  // mesh
  meshTitle: 'Сетка',
  meshNbVertices: 'Активные точки: ',
  meshNbFaces: 'Всего точек: ',

  // topology
  topologyTitle: 'Топология',

  //multires
  multiresTitle: 'Детализация',
  multiresSubdivide: 'Увеличить',
  multiresReverse: 'Реверс',
  multiresResolution: 'Разрешение',
  multiresNoLower: 'Ниже уровня не существует.',
  multiresNoHigher: 'Выше уровня не существует.',
  multiresDelHigher: 'Удалить высокое',
  multiresDelLower: 'Удалить низкое',
  multiresSelectLowest: 'Выберете низкий перед реверсом.',
  multiresSelectHighest: 'Выберете бысокий перед увеличением.',
  multiresWarnBigMesh: function (nbFacesNext) {
    return 'Следующий уровень ' + nbFacesNext + ' faces.\n' +
      'Если вы уверены, снова нажмите на "разрешение".';
  },
  multiresNotReversible: 'К сожалению это не возможно, чтобы изменить эту сетку.\n' +
    'Сетка не продуктивна.',

  // remesh
  remeshTitle: 'Перестроить воксели',
  remeshRemesh: 'Перестроить (Ctrl+X)',
  remeshResolution: 'Разрешение (-X)',
  remeshBlock: 'Блоки-кубики',
  remeshProgress0: 'Инициализация...',
  remeshProgress1: 'Подготовка мешей...',
  remeshProgress2: 'Воксилизация...',
  remeshProgress2Sub: 'Воксилизация...',
  remeshProgress3: 'Заполнение...',
  remeshProgress4SN: 'Surface Nets реконструкция...',
  remeshProgress4MC: 'Marching Cubes реконструкция...',
  remeshProgress5: 'Создание меша...',
  remeshProgress6: 'Тангенциальное сглаживание...',

  // dynamic
  dynamicTitle: 'Динамическая топология',
  dynamicActivated: 'Активировать (без кубиков)',
  dynamicSubdivision: 'Увеличить',
  dynamicDecimation: 'Прореживание',
  dynamicLinear: 'Линейное увеличение',

  // sculpt
  sculptTitle: 'Лепить и красить',
  sculptBrush: '3D Кисть',
  sculptInflate: '3D Надуть',
  sculptTwist: '3D Закручивание',
  sculptSmooth: '3D Сгладить (-Shift)',
  sculptFlatten: '3D Расплющить',
  sculptPinch: '3D Сдавить',
  sculptCrease: '3D Складка',
  sculptDrag: '3D Тянучка',
  sculptMove: '3D Перемещать',
  sculptLocalScale: '3D масштабирование',
  sculptPaint: '2D Кисть',
  sculptMasking: '2D Маска (-Ctrl)',
  sculptTransform: 'Трансформация',
  sculptEditPivot: 'Редактировать пивот',
  sculptClayBuildup: 'Clay Buildup',
  sculptZSphere: 'ZSphere',
  sculptZSphereMode: 'Режим',
  sculptZSphereAddRoot: 'Создать корневую ZSphere',
  sculptZSphereCreateMesh: 'Создать сетку',
  sculptZSphereClear: 'Очистить ZSpheres',

  sculptCommon: 'Общее',
  sculptTool: 'Инструмент',
  sculptSymmetry: 'Симетрия',
  sculptSymmetryMode: 'Координаты',
  sculptSymmetryAxis: 'Ось симметрии',
  sculptSymmetryLocal: 'Локальные',
  sculptSymmetryWorld: 'Мировые',
  sculptContinuous: 'Спрей',
  sculptRadius: 'Размер (-S)',
  sculptIntensity: 'Сила (-A)',
  sculptFocalShift: 'Фокус (Focal Shift)',
  sculptFocalShiftFalloff: 'Спад фокуса (Focal Shift Falloff)',
  sculptHardness: 'Жесткость',
  sculptCulling: 'Тонкая поверхность(передние вершины)',
  sculptAlphaTitle: 'Альфа',
  sculptLockPositon: 'Фиксация',
  sculptAlphaTex: 'Текстура',
  sculptImportAlpha: 'Импорт альфа текстуры (jpg, png...)',
  sculptNegative: 'Негатив (N или -Alt)',
  sculptColor: 'Палитра',
  sculptRoughness: 'Шероховатость',
  sculptMetallic: 'Металлический',
  sculptClay: 'Без учета содержимого',
  sculptAccumulate: 'Наращивать без ограничений',
  sculptSpacing: 'Интервал',
  sculptColorGlobal: 'Глобальный',
  sculptPickColor: 'Пипетка материал (-C)',
  sculptTangentialSmoothing: 'Сглаживание по касательной',
  sculptTopologicalCheck: 'Проверка топологии',
  sculptMoveAlongNormal: 'Перемещать вдоль нормали',
  sculptMaskingClear: 'Очистить (-Ctrl + Drag)',
  sculptMaskingInvert: 'Инверсия (-Ctrl + Click)',
  sculptMaskingBlur: 'Сгладить',
  sculptMaskingSharpen: 'Резко',
  sculptMaskingLasso: 'Выделение лассо',
  sculptPBRTitle: 'PBR материал',
  sculptPaintAll: 'Краска',
  sculptExtractTitle: 'Извлечь',
  sculptExtractThickness: 'Толщина',
  sculptExtractAction: 'Извлечь!',
  sculptTopology: 'Топология',
  sculptTopologyDetail: 'Уровень детализации',
  sculptTopologyDecimate: 'Децимация (упрощение)',

  // states
  stateTitle: 'История',
  stateUndo: 'Назад',
  stateRedo: 'Вперед',
  stateMaxStack: 'Количество шагов',

  // pressure
  pressureTitle: 'Планшет pressure',
  pressureRadius: 'Нажим-размер',
  pressureIntensity: 'Нажим-жесткость',
  pressureInput: 'API планшета',
  pressureInputWindowsInk: 'Windows Ink (PointerEvents)',
  pressureInputWintab: 'Wintab (Wacom)',
  pressureStatusWinTabActive: 'Статус: WinTab Активен',
  pressureStatusWinTabInactive: 'Статус: WinTab Неактивен (нет устройства?)',
  pressureStatusWindowsInk: 'Статус: Windows Ink (PointerEvents)',
  pressureLivePressure: 'Нажим: ',

  // rendering
  renderingTitle: 'Визуализация',
  renderingGrid: 'Показать сетку',
  renderingSymmetryLine: 'Линия симетрии',
  renderingMatcap: null,
  renderingCurvature: 'Рельефность',
  renderingPBR: 'PBR',
  renderingTransparency: 'Прозрачность',
  renderingNormal: 'Карта нормалей',
  renderingUV: 'UV',
  renderingWetClay: 'Мокрая глина',
  renderingWetClayWetness: 'Влажность',
  renderingWetClayBump: 'Рельеф',
  renderingWetClayNoiseScale: 'Масштаб лепки',
  renderingWetClaySSS: 'Полупрозрачность',
  renderingShader: 'Шейдеры',
  renderingMaterial: 'Материал',
  renderingImportUV: 'Импорт (jpg, png...)',
  renderingImportMatcap: 'Импорт (jpg, png...)',
  renderingExtra: 'Дополнительно',
  renderingFlat: 'Плоскости',
  renderingWireframe: 'Каркас',
  renderingExposure: 'Экспозиция',
  renderingEnvironment: 'Отражение',
  renderingIsolate: 'Изолировать / Показать (I)',
  renderingFilmic: 'Пленка',
  renderingQualityTitle: 'Качество изображения',
  renderingNearFarSmooth: 'Стабильность глубины',
  renderingAntialias: 'Сглаживание (нужен перезапуск)',
  renderingAntialiasRestart: 'Сглаживание изменено. Перезагрузить страницу?',

  // contour
  contour: 'Контур',
  contourShow: 'Показать контур',
  contourColor: 'Цвет',
  darkenUnselected: 'Затемнить невыбранное',

  // pixel ratio
  resolution: 'Разрешение',

  // matcaps
  matcapPearl: 'Жемчуг',
  matcapClay: 'Глина',
  matcapSkin: 'Кожа',
  matcapGreen: 'Зеленый',
  matcapWhite: 'Белый',

  // sketchfab
  sketchfabTitle: 'В Sketchfab.com ',
  sketchfabUpload: 'Загрузить',
  sketchfabUploadMessage: 'Ведите API-ключ sketchfab.\n' +
    'Оставьте слово «guest», чтобы загрузить модель анонимно.\n' +
    '(По окончании загрузки и обработки откроется новое окно)',
  sketchfabUploadError: function (error) {
    return 'Ошибка загрузки в Sketchfab :\n' + error;
  },
  sketchfabUploadSuccess: 'Загрузка выполнена !\nВаша ссылка:',
  sketchfabAbort: 'Прервать загрузку?',
  sketchfabUploadProcessing: 'Обработка...\nВаша модель будет доступна после:',

  about: 'О программе',
  measureTitle: 'Измерение отрезками',
  sculptElastic: '3D Эластичный сдвиг',
  sculptElasticity: 'Эластичность',
  sculptCurveDeform: 'Деформация кривой',
  sculptCurveDeformDraw: 'Режим рисования',
  sculptCurveDeformEdit: 'Режим правки',
  sculptCurveDeformClear: 'Очистить кривую',
  measureEnable: 'Активно',
  measureClear: 'Очистить все',
  measureDistanceThickness: 'Толщина по дальности',
  dividerTitle: 'Деление отрезков',
  dividerDivisions: 'Частей деления',
  dividerClear: 'Очистить все',
  sculptDivider: 'Делитель отрезков',

  alphaNone: 'Нет',
  alphaSquare: 'Квадрат',
  alphaSkin: 'Кожа',
  alphaMy8: 'Alpha My8',
  remeshVoxelSize: function (val) {
    return 'Размер ячейки ≈ ' + val;
  },
  remeshResolutionTooHigh: function (maxRes) {
    return 'Разрешение слишком высокое (превышен лимит памяти).\nМаксимальное рекомендуемое разрешение для этой модели: ~' + maxRes + '.';
  },

  // hotkeys HUD
  hudHotkeysTitle: 'Горячие клавиши',
  hudMoveTool: 'move tool',
  hudClayBuildup: 'clay buildup',
  hudCrease: 'crease',
  hudPinch: 'pinch',
  hudTransformTool: 'transform tool',
  hudBrushIntensity: 'brush intensity',
  hudBrushSize: 'brush size',
  hudRemeshResolution: 'remesh resolution',
  hudQuadVoxelRemesh: 'quad voxel remesh',
  hudFocalShift: 'focal shift',
  hudSmooth: 'smooth',
  hudMask: 'mask'
};

export default TR;
