import Enums from '../../misc/Enums.js';
import Brush from './Brush.js';
import Inflate from './Inflate.js';
import Twist from './Twist.js';
import Smooth from './Smooth.js';
import Flatten from './Flatten.js';
import Pinch from './Pinch.js';
import Crease from './Crease.js';
import Drag from './Drag.js';
import Paint from './Paint.js';
import Move from './Move.js';
import Masking from './Masking.js';
import LocalScale from './LocalScale.js';
import Transform from './Transform.js';
import ClayBuildup from './ClayBuildup.js';
import ZSphereTool from './ZSphereTool.js';
import Topology from './Topology.js';
import MeasureTool from '../../measure/MeasureTool.js';
import Elastic from './Elastic.js';
import CurveDeformTool from './CurveDeformTool.js';
import DividerTool from '../../measure/DividerTool.js';
import Visibility from './Visibility.js';
import MaskGradientBlur from './MaskGradientBlur.js';

var Tools = [];

Tools[Enums.Tools.BRUSH] = Brush;
Tools[Enums.Tools.INFLATE] = Inflate;
Tools[Enums.Tools.TWIST] = Twist;
Tools[Enums.Tools.SMOOTH] = Smooth;
Tools[Enums.Tools.FLATTEN] = Flatten;
Tools[Enums.Tools.PINCH] = Pinch;
Tools[Enums.Tools.CREASE] = Crease;
Tools[Enums.Tools.DRAG] = Drag;
Tools[Enums.Tools.PAINT] = Paint;
Tools[Enums.Tools.MOVE] = Move;
Tools[Enums.Tools.MASKING] = Masking;
Tools[Enums.Tools.LOCALSCALE] = LocalScale;
Tools[Enums.Tools.TRANSFORM] = Transform;
Tools[Enums.Tools.CLAYBUILDUP] = ClayBuildup;
Tools[Enums.Tools.ZSPHERE] = ZSphereTool;
Tools[Enums.Tools.TOPOLOGY] = Topology;
Tools[Enums.Tools.MEASURE] = MeasureTool;
Tools[Enums.Tools.ELASTIC] = Elastic;
Tools[Enums.Tools.CURVE_DEFORM] = CurveDeformTool;
Tools[Enums.Tools.DIVIDER] = DividerTool;
Tools[Enums.Tools.VISIBILITY] = Visibility;
Tools[Enums.Tools.MASK_GRADIENT_BLUR] = MaskGradientBlur;

Tools[Enums.Tools.BRUSH].uiName = 'sculptBrush';
Tools[Enums.Tools.INFLATE].uiName = 'sculptInflate';
Tools[Enums.Tools.TWIST].uiName = 'sculptTwist';
Tools[Enums.Tools.SMOOTH].uiName = 'sculptSmooth';
Tools[Enums.Tools.FLATTEN].uiName = 'sculptFlatten';
Tools[Enums.Tools.PINCH].uiName = 'sculptPinch';
Tools[Enums.Tools.CREASE].uiName = 'sculptCrease';
Tools[Enums.Tools.DRAG].uiName = 'sculptDrag';
Tools[Enums.Tools.PAINT].uiName = 'sculptPaint';
Tools[Enums.Tools.MOVE].uiName = 'sculptMove';
Tools[Enums.Tools.MASKING].uiName = 'sculptMasking';
Tools[Enums.Tools.LOCALSCALE].uiName = 'sculptLocalScale';
Tools[Enums.Tools.TRANSFORM].uiName = 'sculptTransform';
Tools[Enums.Tools.CLAYBUILDUP].uiName = 'sculptClayBuildup';
Tools[Enums.Tools.ZSPHERE].uiName = 'sculptZSphere';
Tools[Enums.Tools.TOPOLOGY].uiName = 'sculptTopology';
Tools[Enums.Tools.MEASURE].uiName = 'measureTitle';
Tools[Enums.Tools.ELASTIC].uiName = 'sculptElastic';
Tools[Enums.Tools.CURVE_DEFORM].uiName = 'sculptCurveDeform';
Tools[Enums.Tools.DIVIDER].uiName = 'dividerTitle';
Tools[Enums.Tools.VISIBILITY].uiName = 'sculptVisibility';
Tools[Enums.Tools.MASK_GRADIENT_BLUR].uiName = 'sculptMaskGradientBlur';

Tools[Enums.Tools.BRUSH].icon = 'Brush';
Tools[Enums.Tools.INFLATE].icon = 'Wind';
Tools[Enums.Tools.TWIST].icon = 'RotateCw';
Tools[Enums.Tools.SMOOTH].icon = 'Waves';
Tools[Enums.Tools.FLATTEN].icon = 'ChevronsDownUp';
Tools[Enums.Tools.PINCH].icon = 'Shrink';
Tools[Enums.Tools.CREASE].icon = 'PenLine';
Tools[Enums.Tools.DRAG].icon = 'Move';
Tools[Enums.Tools.PAINT].icon = 'Paintbrush';
Tools[Enums.Tools.MOVE].icon = 'Hand';
Tools[Enums.Tools.MASKING].icon = 'Shield';
Tools[Enums.Tools.LOCALSCALE].icon = 'Expand';
Tools[Enums.Tools.TRANSFORM].icon = 'Grid';
Tools[Enums.Tools.CLAYBUILDUP].icon = 'Layers';
Tools[Enums.Tools.ZSPHERE].icon = 'CircleDot';
Tools[Enums.Tools.TOPOLOGY].icon = 'Network';
Tools[Enums.Tools.MEASURE].icon = 'Ruler';
Tools[Enums.Tools.ELASTIC].icon = 'Activity';
Tools[Enums.Tools.CURVE_DEFORM].icon = 'Spline';
Tools[Enums.Tools.DIVIDER].icon = 'Scissors';
Tools[Enums.Tools.VISIBILITY].icon = 'Eye';
Tools[Enums.Tools.MASK_GRADIENT_BLUR].icon = 'Blend';

export default Tools;
